### ISSUE TITLE
No "noData" support yet?

### ISSUE THREAD

**Issue by paoloavezzano** [marcaube/ObHighchartsBundle#57]
I was trying to add a noData message via:

```
$ob->lang->noData('Message');
$ob->noData->style(array(/* … */));
```

…but I get the alert

*Undefined property: Ob\HighchartsBundle\Highcharts\Highchart::$noData*

I can't find any `noData` code around, is it planned anytime soon?

**Comment by marcaube** [comment]
I don't have any "plans", but it'd be easy to add support for the `noData` option, I can probably find a couple of minutes this week to do it.

**Comment by paoloavezzano** [comment]
Thanks a lot, appreciated.

**Comment by marcaube** [comment]
@paoloavezzano Support added in master branch, tell me if it works properly for you

```php
$chart->lang->noData('Message');
$chart->noData->style(array(
    'fontSize' => '12px'
));
```

**Comment by paoloavezzano** [comment]
On a first attempt nothing was showing as I forgot to load the proper module.
Once loaded everything worked correctly. Thanks a lot!

**Comment by marcaube** [comment]
Perfect!
