### ISSUE TITLE
Function yAxis.plotlines not recognize

### ISSUE THREAD

**Issue by falexis77** [marcaube/ObHighchartsBundle#58]
Hello,

First, sorry for my poor english!
So, i have a problem when i want to use the function "plotlines".
http://api.highcharts.com/highcharts#yAxis.plotLines
I have a error about this, urecognized by symfony2.
I looking for on the bundle but i don't find it.

Are you included in your bundle ?

thank you in advance for your reply

**Comment by marcaube** [comment]
I'm guessing from your GitHub profile that you speak french.

---

Salut, peux-tu copier-coller ici l'erreur retournée par Symfony ? Pourrais-tu aussi me montrer le code php que tu utilise pour générer le graphique ? L'erreur pourrait bien provenir de là.

Je suis allé voir le lien et nulle part dans leurs exemples ils ne placent une ligne sur l'axe des Y, c'est un peu étrange. J'ai refait leur [premier exemple](http://jsfiddle.net/gh/get/jquery/1.7.2/highslide-software/highcharts.com/tree/master/samples/highcharts/xaxis/plotlines-color/) en php et voici le code que ça me donne :

```php
$chart = new Highchart();
$chart->chart->renderTo('container');
$chart->chart->type('column');
$chart->xAxis->categories(array('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'));
$chart->xAxis->plotLines(array(
    array(
        'color' => '#F00',
        'width' => 2,
        'value' => 5.5
    )
));
$chart->series(array(
    array('data' => array(29.9, 71.5, 106.4, 129.2, 144.0, 176.0, 135.6, 148.5, 216.4, 194.1, 95.6, 54.4))
));
```

**Comment by falexis77** [comment]
Bonjour, 
Pour commencer, désolé pour la réponse tardive!
Je me suis trompé effectivement, j'ai contourné le problème en utilisant "scatter" en mettant la même valeur dans le tableau data.
Pour l'expérience utilisateur, j'utilise window.history.pushState pour modifier dynamiquement l'url et afficher les graph sans rechargement de la page. J'utilise également le FOSJSRouting bundle pour mes routes. Seulement, les graph sont vides et j'ai des erreurs.

<pre><code>
$(".tabs").on("click",function() {
        var id = this.id;
        var main = $("html");
            window.history.pushState({}, '', Routing.generate('infos_villes', {'id': id}), true);
            main.load(Routing.generate('infos_villes', {'id': id}), true);
            return false;
        }
    });
</code></pre>

l'erreur au niveau de Highcharts
<pre><code>
TypeError: y.body is null
</code></pre>

On est obligé de recharger la page pour l'affichage des graphiques ?

**Comment by marcaube** [comment]
Cas intéressant ! Je n'ai jamais généré de graphiques dynamiquement, mais ça doit être possible.

Il va falloir garder une référence de l'objet Highcharts dans le *scope* de ton code en utilisant `{{ chart(chart, false) }}`, qui fait le rendu sans la fonction anonyme de jQuery. Par défaut, la référence aura le nom de l'élément dans lequel tu as placé le graphique. E.g.

```php
// Dans le contrôleur
$chart = new Highchart();
$chart->chart->renderTo('machin');
```

```js
// Ce que donne "{{ chart(chart, false) }}" dans la vue
var machin = new Highcharts.Chart({
    // ...
});
```

Ensuite, il faut remplacer les *series* avec les nouvelles données récupérées au *pushstate*/*popstate* et puis forcer Highcharts à refaire le rendu.

```js
// Récupère les nouvelles données
var data = [1, 2, 3];

// Remplace les séries
machin.series.setData(data, true);

// Re-dessine le graph
machin.redraw();
```

Je n'ai pas vérifié mais c'est comme ça que je m'y prendrais en regardant rapidement la doc :
- [setData](http://api.highcharts.com/highcharts#Series.setData)
- [redraw](http://api.highcharts.com/highcharts#Chart.redraw)

**Comment by marcaube** [comment]
@falexis77 est-ce que ça a marché ?
