### ISSUE TITLE
chart rendering only work for linechart

### ISSUE THREAD

**Issue by Sacredila** [marcaube/ObHighchartsBundle#59]
Hello, I have a problem with charts other than 'linechart'.
I installed the bundle via composer, added it to bundles list in AppKernel then in a controller I tried to
test examples of CookBook. The first example with $ob->chart->renderTo('linechart'); worked fine but for all other examples, it displays nothing.
I don't know what the problem comes from, can you help me please ? Thanks

**Comment by marcaube** [comment]
Can you provide code samples? What's your code for the charts that do not work?

**Comment by juarezelias** [comment]
I have the same problem. 
I my case just the example of Pie chart with Drilldown work. All others, examples in "usage" and "cookbook" it displays nothing.
Marcaube, can you check this please?

**Comment by marcaube** [comment]
How's your html? 

If your chart container has a `#linechart` id, e.g. `<div id="linechart"></div>` then your php code need to use the same id, e.g. `$chart->chart->renderTo('linechart');`. Do you have any JS error in your browser console?

I can't help much if you don't give me more context. Show me code samples, php and html. I'd like to help but if I can't reproduce a bug, I can't fix it.

**Comment by juarezelias** [comment]
sorry for my mistake, I was wrong about my id name.

Thanks for your fast reply.


From:  Marc Aubé <notifications@github.com>
Reply-To:  marcaube/ObHighchartsBundle
<reply+00629db9c4a5e5b6782d96c8230fd0e1e7374487b01edbd792cf00000001110a05799
2a169ce0372051f@reply.github.com>
Date:  sábado, 28 de fevereiro de 2015 19:38
To:  marcaube/ObHighchartsBundle <ObHighchartsBundle@noreply.github.com>
Cc:  Juarez Elias  Penna <juarez@designus.com.br>
Subject:  Re: [ObHighchartsBundle] chart rendering only work for linechart
(#59)


How's your html? 

If your chart container has a #linechart id, e.g. <div id="linechart"></div>
then your php code need to use the same id, e.g.
$chart->chart->renderTo('linechart');. Do you have any JS error in your
browser console?

I can't help much if you don't give me more context. Show me code samples,
php and html. I'd like to help but if I can't reproduce a bug, I can't fix
it.

‹
Reply to this email directly or view it on GitHub
<https://github.com/marcaube/ObHighchartsBundle/issues/59#issuecomment-76552
827> .
