### ISSUE TITLE
rangeSelector and translation

### ISSUE THREAD

**Issue by cassianotartari** [marcaube/ObHighchartsBundle#61]
First, many thanks by the bundle!
Second, I'm starting with highcharts and I'm trying to create something similar to this http://jsfiddle.net/9xpekowg/3/ adding translations and datetime range filters. The objective is create an interface to visualize page views in my system. Didn't figure out also how to translate highcharts using ``ObHighchrtsBundle``. Now my page views charts are like this:

![screenshot from 2015-03-19 14 50 40](https://cloud.githubusercontent.com/assets/3017642/6736996/5c82a5ca-ce47-11e4-97d6-ef3c518d740c.png)

```php
$ob = new Highchart();
$ob->chart->alignTicks(false);
$ob->chart->renderTo('linechart');
$ob->title->text('Visitas');
$ob->xAxis->title(array('text' => ""));
$ob->xAxis->type('datetime');
$ob->xAxis->tickInterval((24 * 3600 * 1000));
$ob->yAxis->title(array('text' => ""));
$ob->yAxis->min(0);
$ob->series($series);
```

```js
 $(function () {
    var linechart = new Highcharts.Chart({
        chart: {"alignTicks":false,"renderTo":"linechart"},
        plotOptions: {"series":[]},
        series: [{"name":10766,"data":[[1425870000000,30],[1426042800000,20],[1426215600000,4]]}], 
        title: {"text":"Visitas"},
        xAxis: {"title":{"text":""},"type":"datetime","tickInterval":86400000},
        yAxis: {"title":{"text":""},"min":0}
    });
});
```

I don't know also why ``strtotime('2015-03-13'))*1000`` return an date to chart with hour ``3:00`` but this seems to be an php issue and related to timezone. (EDITED: adding ``GMT`` to the string the hour issue is solved, in the above example: ``strtotime('2015-03-13 GMT'))*1000``)

**Comment by cassianotartari** [comment]
Language set by:
```php
        $ob->lang->lang(array(
                'months' => array('Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'),
                'shortMonths' => array('Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez'),
                'weekdays' => array('Domingo', 'Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado'),
                'loading' => array('Atualizando o gráfico...aguarde'),
                'contextButtonTitle' => array('Exportar gráfico'),
                'decimalPoint' => array(','),
                'thousandsSep' => array('.'),
                'downloadJPEG' => array('Baixar imagem JPEG'),
                'downloadPDF' => array('Baixar imagem PNG'),
                'downloadSVG' => array('Baixar vetor SVG'),
                'printChart' => array('Imprimir gráfico'),
                'rangeSelectorFrom' => array('De'),
                'rangeSelectorTo' => array('Para'),
                'rangeSelectorZoom' => array('Zoom'),
                'resetZoom' => array('Limpar Zoom'),
                'resetZoomTitle' => array('Voltar Zoom para nível 1:1')
        ));
```

The ``js`` returned:
```js
$(function () {
    Highcharts.setOptions({lang: {"lang":{"months":["Janeiro","Fevereiro","Mar\u00e7o","Abril","Maio","Junho","Julho","Agosto","Setembro","Outubro","Novembro","Dezembro"],"shortMonths":["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"],"weekdays":["Domingo","Segunda","Ter\u00e7a","Quarta","Quinta","Sexta","S\u00e1bado"],"loading":["Atualizando o gr\u00e1fico...aguarde"],"contextButtonTitle":["Exportar gr\u00e1fico"],"decimalPoint":[","],"thousandsSep":["."],"downloadJPEG":["Baixar imagem JPEG"],"downloadPDF":["Baixar imagem PNG"],"downloadSVG":["Baixar vetor SVG"],"printChart":["Imprimir gr\u00e1fico"],"rangeSelectorFrom":["De"],"rangeSelectorTo":["Para"],"rangeSelectorZoom":["Zoom"],"resetZoom":["Limpar Zoom"],"resetZoomTitle":["Voltar Zoom para n\u00edvel 1:1"]}},
    });
```

Just don't understand why it didn't translated my chart... :(

**Comment by marcaube** [comment]
Hi Cassiano,

I'll have more time to look at this on the weekend but after a quick look, it seems like the example you posted is using Highstock. There is a class inside the bundle named `Ob\HighchartsBundle\Highcharts\Highstock` with support for the `rangeSelector` used in the example.

I hope it gives you a push in the right direction, before I can give you a more elaborate answer this weekend.

**Comment by cassianotartari** [comment]
Thanks @marcaube I've tried before ``Highstock`` but I can't run even a single example:
```php
$ob = new \Ob\HighchartsBundle\Highcharts\Highstock();
$ob->chart->renderTo('linechart');
$ob->rangeSelector->selected(1);
$series = array('name' => 'test', 'data' => array(7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6));
$ob->series($series);
```
The result:
```js
$(function () {
    var chart = new Highcharts.StockChart({
        chart: {"renderTo":"linechart"},
        rangeSelector: {"selected":1},
        series: {"name":"test","data":[7,6.9,9.5,14.5,18.2,21.5,25.2,26.5,23.3,18.3,13.9,9.6]}, 
    });
});
```
What I noticed is that in other examples the function starts like this:
```js
$('#container').highcharts('StockChart'
```

**Comment by cassianotartari** [comment]
Huge mistake, forget to add ``highstock.js`` to template, my bad...

But keeping the issue to create the ``Highstock`` example from ``jsfiddle``, is there a way to use ``$.getJSON(`` with a url to feed my chart using the bundle?

**Comment by marcaube** [comment]
Alright, we had to get a little creative here. Two things are needed for this to work:
- We have to wrap our chart code with the `getJSON` function
- We have to pass a variable to set our series data

In 2.0, they changed how we configure a chart to fetch data via AJAX, but it's still pretty simple. We have to render the chart without the jQuery anonymous function (i.e. `$(function () {});`) by using the second argument of the `chart` function in twig.

```html
<script type="text/javascript">
    $.getJSON('http://www.highcharts.com/samples/data/jsonp.php?filename=aapl-v.json&callback=?', function (data) {
        {{ chart(chart, false) }}
    });
</script>
```

Notice the `data` variable passed to the callback function, that's the variable we have to use for our series data. In PHP, we'll have to use `Zend\Json\Expr` to encode the variable name, or else it will be passed as a string.

```php
public function chartAction()
{
    $chart = new Highstock();
    $chart->chart->renderTo('linechart');
    $chart->rangeSelector->selected(1);
    $chart->series(array(
        array('data' => new \Zend\Json\Expr('data'))
    ));

    return array("chart" => $chart);
}
```

Hope this solves your problem!

**Comment by cassianotartari** [comment]
Cool @marcaube ! The example works like a charm!

Now I will code the controller action to return data to chart, thanks!

**Comment by marcaube** [comment]
Great! Happy coding!

**Comment by abirbourounia** [comment]
Hello @marcaube ,
I'm wondering if u can tell us the steps to customize obhighchart bundle, a full documentation for example.
I wanna find a solution to make a real time chart , I tried to fix it but it doesn't work.
thank you so much =)
