### ISSUE TITLE
Set theme for chart

### ISSUE THREAD

**Issue by alexloehner** [marcaube/ObHighchartsBundle#63]
Hello,

This already was nswered in a closed issue some time ago, but the solution posted there doesn't work for me.

First of all, I'm on Symfony 2.6.6 with "ob/highchartsbundle": "dev-master", so I'm up to date.
I'm creating two charts and both are working absolutly fine.

But adding the theme to the javascript, nothing happens. The charts are still working, and no color changes happen.

Instead I get a Javascript error in the console:

    Uncaught TypeError: chart_registrations_per_day.setOptions is not a function

This is the relevant part of my twig file:

    <div class="panel-body">

        <script src="//code.highcharts.com/4.0.1/highcharts.js"></script>
        <script src="//code.highcharts.com/4.0.1/modules/exporting.js"></script>

        <script type="text/javascript">
            $(function(){

                {{ chart(chart_registrations_per_day, false) }}
                {{ chart(chart_machines_per_day, false) }}

                Highcharts.theme = {
                    colors: ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572',
                        '#FF9655', '#FFF263', '#6AF9C4'],
                    chart: {
                        backgroundColor: {
                            linearGradient: [0, 0, 500, 500],
                            stops: [
                                [0, 'rgb(255, 255, 255)'],
                                [1, 'rgb(240, 240, 255)']
                            ]
                        }
                    }
                };

                chart_registrations_per_day.setOptions(Highcharts.theme);
                chart_machines_per_day.setOptions(Highcharts.theme);

            });
        </script>
        <div id="chart_registrations_per_day" style=""></div>
        <div id="chart_machines_per_day" style=""></div>

    </div>

And here is how it looks like when it is fully rendered:

    <div class="panel-body">

        <script src="//code.highcharts.com/4.0.1/highcharts.js"></script>
        <script src="//code.highcharts.com/4.0.1/modules/exporting.js"></script>

	<script type="text/javascript">
	    $(function(){

		var chart_registrations_per_day = new Highcharts.Chart({
			chart: {"renderTo":"chart_registrations_per_day","zoomType":"x","type":"area"},
			legend: {"enabled":false},
			plotOptions: {"area":{"allowPointSelect":true,"dataLabels":{"enabled":false},"showInLegend":true}},
			series: [{"name":"User registrations","data":[.........]}], 
			title: {"text":"Registrations per day"},
			xAxis: {"title":{"text":"Date"},"type":"datetime"},
			yAxis: {"title":{"text":"Registrations per day"}}
	    	});

		var chart_machines_per_day = new Highcharts.Chart({
			chart: {"renderTo":"chart_machines_per_day","zoomType":"x","type":"area"},
			legend: {"enabled":false},
			plotOptions: {"area":{"allowPointSelect":true,"dataLabels":{"enabled":false},"showInLegend":true}},
			series: [{"name":"Machine registrations","data":[........]}], 
			title: {"text":"Machines per day"},
			xAxis: {"title":{"text":"Date"},"type":"datetime"},
			yAxis: {"title":{"text":"Machines per day"}}
	    	});

		Highcharts.theme = {
		    colors: ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572',
		        '#FF9655', '#FFF263', '#6AF9C4'],
		    chart: {
		        backgroundColor: {
		            linearGradient: [0, 0, 500, 500],
		            stops: [
		                [0, 'rgb(255, 255, 255)'],
		                [1, 'rgb(240, 240, 255)']
		            ]
		        }
		    }
		};

		chart_registrations_per_day.setOptions(Highcharts.theme);
		chart_machines_per_day.setOptions(Highcharts.theme);

	    });
	</script>
	<div id="chart_registrations_per_day" style=""></div>
        <div id="chart_machines_per_day" style=""></div>
    </div>

Any help would be really appreciated here.

**Comment by alexloehner** [comment]
Oh... I've of course also tried:

    Highcharts.setOptions(Highcharts.theme);

without any success.

**Comment by marcaube** [comment]
Sorry for the wait, I will have a look at it before the end of the week.

**Comment by adm-husker** [comment]
Hi, same problem here : )

**Comment by marcaube** [comment]
Alright, I'll keep you posted.

**Comment by marcaube** [comment]
@alexloehner and @adm-husker,  I was successful using `Highcharts.setOptions(Highcharts.theme);`, but the trick is that the theme must be set before a chart is rendered. Also, it has to be set "globally" by calling `setOptions` on the Highcharts library, not on an individual chart object.

```html
<script type="text/javascript">
    $(function () {
        Highcharts.theme = {
            colors: ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
            chart: {
                backgroundColor: {
                    linearGradient: [0, 0, 500, 500],
                    stops: [
                        [0, 'rgb(255, 255, 255)'],
                        [1, 'rgb(240, 240, 255)']
                    ]
                }
            }
        };
        Highcharts.setOptions(Highcharts.theme);

        {{ chart(chart_registrations_per_day, false) }}
        {{ chart(chart_machines_per_day, false) }}
    });
</script>
```

I hope that helps!

**Comment by alexloehner** [comment]
hmm... well, I'm sorry, but for me it doesn't work as you can see here:  http://test.linuxcounter.net/statistics/counter  :(

I'm trying to apply the same theme for the area as in the highcharts demo here:  http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/line-time-series/

The related oart in the twig template is this:

	<div class="panel-body">

	    <script src="//code.highcharts.com/highcharts.js"></script>
	    <script src="//code.highcharts.com/modules/exporting.js"></script>

	    <script type="text/javascript">
		$(function(){

		    Highcharts.theme = {
		        area: {
		            fillColor: {
		                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
		                stops: [
		                    [0, Highcharts.getOptions().colors[0]],
		                    [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
		                ]
		            },
		            marker: {
		                radius: 2
		            },
		            lineWidth: 1,
		            states: {
		                hover: {
		                    lineWidth: 1
		                }
		            },
		            threshold: null
		        }
		    };

		    Highcharts.setOptions(Highcharts.theme);

		    {{ chart(chart, false) }}

		});
	    </script>
	    <div id="chart_registrations_per_month" style=""></div>

	</div>


The rendered source code is this:

	<div class="panel-body">

	    <script src="//code.highcharts.com/highcharts.js"></script>
	    <script src="//code.highcharts.com/modules/exporting.js"></script>

	    <script type="text/javascript">
		$(function(){

		    Highcharts.theme = {
		        area: {
		            fillColor: {
		                linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
		                stops: [
		                    [0, Highcharts.getOptions().colors[0]],
		                    [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
		                ]
		            },
		            marker: {
		                radius: 2
		            },
		            lineWidth: 1,
		            states: {
		                hover: {
		                    lineWidth: 1
		                }
		            },
		            threshold: null
		        }
		    };

		    Highcharts.setOptions(Highcharts.theme);

		    var chart_registrations_per_month = new Highcharts.Chart({
			chart: {"renderTo":"chart_registrations_per_month","zoomType":"x","type":"line"},
			legend: {"enabled":true},
			plotOptions: {"area":{"allowPointSelect":true,"dataLabels":{"enabled":false},"showInLegend":true}},
			series: [{"type":"area","name":"User Registrations","data":[......]},{"type":"area","name":"Machine Registrations","data":[......]}], 
			subtitle: {"text":"Click and drag in the plot area to zoom in"},
			title: {"text":"Registrations per month"},
			xAxis: {"title":{"text":"Date"},"type":"datetime","minRange":36288000000},
			yAxis: {"min":0,"title":{"text":"Registrations per month"}}
			});

		});
	    </script>
	    <div id="chart_registrations_per_month" style=""></div>

	</div>

**Comment by marcaube** [comment]
The theme is not defined quite correctly, try this:

```html
<script type="text/javascript">
    $(function () {
        Highcharts.theme = {
            colors: ['#058DC7', '#50B432', '#ED561B', '#DDDF00', '#24CBE5', '#64E572', '#FF9655', '#FFF263', '#6AF9C4'],
            plotOptions: {
                series: {
                    fillColor: {
                        linearGradient: [0, 0, 0, 300],
                        stops: [
                            [0, Highcharts.getOptions().colors[0]],
                            [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                        ]
                    },
                    marker: {
                        radius: 2
                    },
                    lineWidth: 1,
                    states: {
                        hover: {
                            lineWidth: 1
                        }
                    },
                    threshold: null
                }
            }
        };
        Highcharts.setOptions(Highcharts.theme);

        {{ chart(chart_registrations_per_day, false) }}
        {{ chart(chart_machines_per_day, false) }}
    });
</script>
```

You can check [Highcharts API reference](http://api.highcharts.com/highcharts) for the configuration options.

**Comment by alexloehner** [comment]
Ahh... now that is working! Great! Thanks a lot! ;)

**Comment by marcaube** [comment]
You're welcome!
