### ISSUE TITLE
blank charts without any error messages

### ISSUE THREAD

**Issue by alexloehner** [marcaube/ObHighchartsBundle#64]
Hello,

I've created some funny statistics for the internals of the Linux Kernels here:
  https://www.linuxcounter.net/statistics/kernel

Unfortunatly with all the data (1046 entries per chart) the charts are all blank.

With about 700 entries per chart I got the charts correctly working, but now with all database entries, the charts are blank.

I get no errors, nothing in Javascript console (I thought about wrong sorting, but that doesn't seem the reason), nothing in prod.log, nothing in error_log, nothing in php-error.log.

So, I really would appreciate any help here. You can see the rendered code on the page with the link above.

**Comment by alexloehner** [comment]
Here it also is in jsfiddle with the same problem:   http://jsfiddle.net/alexloehner/y3w4t7gk/

**Comment by alexloehner** [comment]
Okay... through try&error I've now found out, that 1000 entries are working and 1001 entries and more are not working.... so is there a highcharts limit of 1000 data entries???

**Comment by alexloehner** [comment]
sorry... I'm really sorry... I should consider to use google the more and do more try and error before posting a bug... :-P

'turboThreshold'  => 2000

in plotOptions did the job.

**Comment by marcaube** [comment]
Glad you found an answer, I've been pretty busy in the last week.
