### ISSUE TITLE
Any plan for integrating HighMaps?

### ISSUE THREAD

**Issue by 94noni** [marcaube/ObHighchartsBundle#66]
Hi,

Any plan for integrating [HighMaps](http://www.highcharts.com/maps/demo)?

It could be useful :)

Thanks

**Comment by marcaube** [comment]
Indeed, it could be useful, but I don't use it. Nice opportunity for a PR though :wink:

**Comment by 94noni** [comment]
I will try to find time to make one 
Or if someone see this and propose its own :)
