### ISSUE TITLE
I cannot rotate category labels on the x axis

### ISSUE THREAD

**Issue by dmlmdev** [marcaube/ObHighchartsBundle#69]
Hi,

I am trying to rotate the labels on the xAxis so that the text runs vertically instead of horizontally but I cannot seem to do this and I cannot see an example of this.

My code is something like:  
// Chart
        $series = array(
            array("name" => "nb results",    "data" => $values)
        );

        $ob = new Highchart();
        $ob->chart->renderTo('linechart');  // The #id of the div where to render the chart
        $ob->title->text('Daily Query Results');
        $ob->xAxis->title(array('text'  => "Date"));
        $ob->xAxis->categories($categories);
        $ob->xAxis->type('datetime');

        $ob->xAxis->labels->rotation(45);

        $ob->yAxis->title(array('text'  => "Results"));
        $ob->series($series);

If i do not try and rotate the labels it works fine but the instant i try and rotate the labels it throws a :

500 Notice: Undefined property: stdClass::$labels

How should I be rotating the category labels on the xAxis?

Kind Regards

**Comment by marcaube** [comment]
```php
// try
$ob->xAxis->labels(array('rotation' => 45));
```

**Comment by dmlmdev** [comment]
Perfect. Thank you

**Comment by marcaube** [comment]
Great!
