### ISSUE TITLE
Pass options by array

### ISSUE THREAD

**Issue by aMakdessi** [marcaube/ObHighchartsBundle#75]
Hi,

I'm trying to pass options by array, but I get an exception (`Notice: Trying to get property of non-object`) :

``` php
//This don't work : 
$ob = new Highchart();
$ob->title([
    'text' => 'Some text',
    'style' => [
        'color' => '#ab3f41',
        'fontWeight' => 'bold',
    ]
]);
//This works : 
$ob->title->text('Some text');
$ob->title->style([
    'color' => '#ab3f41',
    'fontWeight' => 'bold',
]);
```

The strange thing is that the following code works : 

``` php
$ob->xAxis([
    'title' => ['text'  => 'X axis'],
    'tickInterval' => 1,
]);
```

Am I doing something wrong ? 
I'm using SF 2.8 and ob/highcharts-bundle 1.3

**Comment by marcaube** [comment]
I don't like the way it works either...

`title` is an object (`ChartOption`), `text` and `style` are properties on this object. When rendered, `title` is simply json encoded, so you would think that passing the options as an array would work, e.g.

```php
$a = new stdClass;
$a->text = 'foo';
json_encode($a); // {"text":"foo"}

$b = ['text' => 'foo'];
json_encode($b); // {"text":"foo"}
```

The thing is, `text` and `style` are actually properties on an `stdClass`, which is a property on `ChartOption` (:boom: mindblown :boom:). So when you call `$ob->title->text('Some text');`, behind the scene, a magic method (`__call`) transforms the method call to `$ob->title->title->text`.

If it works with `xAxis`, there is probably a way to do it with `title` too, but I'd have to fiddle with it to figure it out.

**Comment by HanSolo79** [comment]
Hi,
I post here because i think my problem is similary.
I had a functionnal pieChart before migrate on Symfony2 and i can't do again now.

How can i pass this options to the graph object in my Controller ?

plotOptions: {
     pie: {
     allowPointSelect: true,
     cursor: 'pointer',
     dataLabels: 
          { enabled: false },
     showInLegend: true
     }
},

Need i encode the options in json before send it to the graph object ?
Can you give me a  symfony2 exemple of this options type for i can continue learning please ?

I'm using SF 2.7 and ob/highcharts-bundle 1.3.

Regards,

**Comment by silentgecko** [comment]
i also want to add plotOptions... but dunno how.

cane we make this possible? :D

**Comment by marcaube** [comment]
@aMakdessi I have not had the time to figure the problem yet with passing options by array. I'm going to to leave the issue open and come back to it.

@HanSolo79 Check the [piechart example](https://github.com/marcaube/ObHighchartsBundle/blob/master/Resources/doc/cookbook.md#pie-chart-with-legend) in the Cookbook, it has the exact same options passed to `plotOptions`.

@silentgecko check in the [Cookbook](https://github.com/marcaube/ObHighchartsBundle/blob/master/Resources/doc/cookbook.md), there are many examples using `plotOptions`.
