### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by Hesiode** [marcaube/ObHighchartsBundle#76]
What about Symfony 3 ?
Thank you

**Comment by marcaube** [comment]
I have not tested this bundle in a Symfony 3 app, but I'm pretty sure we could simply update the version constraint in `composer.json` and it would work. You could give that a try. I will try to look a it soon.

**Comment by vinujan59** [comment]
I am new to symfony what are thr version constraints i sholud update

**Comment by marcaube** [comment]
In `composer.json`, the version constraint should be `"symfony/symfony": "~2.3|~3.0"` instead of `"symfony/symfony": "~2.3"`.

**Comment by vinujan59** [comment]
Thank you very much

**Comment by vinujan59** [comment]
When i run "composer require ob/highcharts-bundle"

command prompt gives this

Using version ^1.3 for ob/highcharts-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: symfony/symfony[v2.3.0, v3.0.0].
    - Can only install one of: symfony/symfony[v3.0.0, v2.3.0].
    - Can only install one of: symfony/symfony[v2.3.0, v3.0.0].
    - ob/highcharts-bundle 1.3 requires symfony/symfony ~2.3 -> satisfiable by symfony/symfony[v2.3.0].
    - Installation request for ob/highcharts-bundle ^1.3 -> satisfiable by ob/highcharts-bundle[1.3].
    - Installation request for symfony/symfony == 3.0.0.0 -> satisfiable by symfony/symfony[v3.0.0].


Installation failed, reverting ./composer.json to its original content.
---------------------------------------------------------------------------------------------------
my composer.json looks like this
  "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "2.3|3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev"
    },

please give me a fix!

**Comment by marcaube** [comment]
I just released a new tag with support for Symfony 3.

**Comment by elyesj** [comment]
When i run "composer require ob/highcharts-bundle"

command prompt gives this

Using version ^1.3 for ob/highcharts-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

Problem 1
- Can only install one of: symfony/symfony[v2.3.0, v3.0.0].
- Can only install one of: symfony/symfony[v3.0.0, v2.3.0].
- Can only install one of: symfony/symfony[v2.3.0, v3.0.0].
- ob/highcharts-bundle 1.3 requires symfony/symfony ~2.3 -> satisfiable by symfony/symfony[v2.3.0].
- Installation request for ob/highcharts-bundle ^1.3 -> satisfiable by ob/highcharts-bundle[1.3].
- Installation request for symfony/symfony == 3.0.0.0 -> satisfiable by symfony/symfony[v3.0.0].

Installation failed, reverting ./composer.json to its original content.
my composer.json looks like this
"require": {
"php": ">=5.5.9",
"symfony/symfony": "2.3|3.0.*",
"doctrine/orm": "^2.5",
"doctrine/doctrine-bundle": "^1.6",
"doctrine/doctrine-cache-bundle": "^1.2",
"symfony/swiftmailer-bundle": "^2.3",
"symfony/monolog-bundle": "^2.8",
"sensio/distribution-bundle": "^5.0",
"sensio/framework-extra-bundle": "^3.0.2",
"incenteev/composer-parameter-handler": "^2.0",
"friendsofsymfony/user-bundle": "~2.0@dev"
},
please if someone have a solution please help me
