### ISSUE TITLE
Javascript call back 

### ISSUE THREAD

**Issue by hounded** [marcaube/ObHighchartsBundle#79]
Hi i'm trying to replicate the following 

http://jsfiddle.net/gh/get/jquery/1.9.1/highslide-software/highcharts.com/tree/master/samples/highcharts/demo/gauge-activity/

I'm getting stuck at function callback, how exactly to I add this?

**Comment by marcaube** [comment]
Interesting, it's the first time I hear of this callback function. It seems like it was introduced in [Highcharts 2.3](http://www.highcharts.com/docs/extending-highcharts/extending-highcharts), which is a good while ago. Never had to use it so I must've missed it.

The current wrapper implementation does not support this callback. It could be easy to add, but [encoding](https://github.com/marcaube/ObHighchartsBundle/blob/master/Resources/doc/usage.md#use-a-javascript-anonymous-function) as much JS in PHP will feel a bit dirty.

**Comment by hounded** [comment]
Hi, thanks for the quick response, please forgive me if i'm making a hash of this but from what I can see 

the function sits as a global to highcharts, and there is no way add it, i've tried 

     use Zend\Json\Expr;

      $function = new Expr(' function callback() {
       }');

        $ob->global(
            $function
        );

also 

        $ob->chart->events(
            array('load'=>$function)
        );

am I missing something, I have looked right through the api and can't find where I would add the function

**Comment by marcaube** [comment]
Well, from what I can tell, it's passed as the third argument to the chart function in JS, i.e.

```js
$(function () {
    Highcharts.chart('container', {
        // chart config and data
    },
    function callback() {
        // ...
    });
});
```

The encoded callback function would have to be inserted at the end of the [render() function](https://github.com/marcaube/ObHighchartsBundle/blob/master/Highcharts/Highchart.php#L96) in `Ob\HighchartsBundle\Highcharts\Highchart`, which is not possible at the moment.
