### ISSUE TITLE
Chart to image in the controller ??

### ISSUE THREAD

**Issue by joeljv91** [marcaube/ObHighchartsBundle#80]
The generated chart can be exported in to an image file directly without clicking the export button in the generated view?

Thanks.

**Comment by marcaube** [comment]
No it is not possible, sorry. The chart rendering is all done in JS, and this projet is only a thin PHP wrapper around it. Would be cool though :stuck_out_tongue_closed_eyes:

**Comment by joeljv91** [comment]
Thanks for the answer. I'm going to do this converting the html response to PNG with [https://github.com/KnpLabs/KnpSnappyBundle](url)
