### ISSUE TITLE
3D options

### ISSUE THREAD

**Issue by jul6art** [marcaube/ObHighchartsBundle#89]
Hi, i really enjoy your bundle, i made an analytic bundle for symfony3 using your bundle.

Here it is: https://bitbucket.org/jul6art/gkratzanalyticbundle

Now, i 'm waiting for using the new 3dpie and 3ddonuts etc... from highcharts.

Is it planned? Thx for your good stuffs

**Comment by tiranflorin** [comment]
Hi, I also would like to be able to use 3dpie with this bundle. Thanks!

**Comment by marcaube** [comment]
From what I gather, we'd only need to add `options3d`. Right now, there is no support for this option and I don't have time to do it (merge requests are welcome though 😉).

But, you can *fake* it if you want using an `stdClass` object.

```php
// the options3d values
$option = new \stdClass();
$option->enabled = true;
$option->alpha = 45;
$option->beta = 0;

$chart = new Highchart();
$chart->chart->renderTo('container');
$chart->chart->type('pie');
$chart->chart->options3d($option);
$chart->title->text('Browser market shares at a specific website, 2014');

$chart->plotOptions->pie([
    'depth' => 35,
]);

$chart->series([[
    'name'        => 'Browser share',
    'data'        => [
        ['Firefox', 45.0],
        ['IE', 26.8],
        [
            'name' => 'Chrome',
            'y' => 12.8,
            'sliced' => true,
            'selected' => true,
        ],
        ['Safari', 8.5],
        ['Opera', 6.2],
        ['Others', 0.7]
    ],
]]);
```

This would give you a chart that looks like this : 

![screen shot 2016-12-07 at 5 50 15 pm](https://cloud.githubusercontent.com/assets/1478986/20990229/bf36f5ec-bca5-11e6-8c18-960220746b9e.png)

**Comment by tiranflorin** [comment]
Hello guys,

I managed to make it work without "faking" it with stdClass.
It works with arrays. The problem on my side was that I forgot to include the 3d js script (aparently it is required).

So, the difference between using a normal pie chart and a 3d one reduced to adding:

`$ob = new Highchart();`
`$ob->chart->options3d(array(`
`'enabled' => true,`
`'alpha' => 45,`
 `'beta' => 0`
`));`

and the missing js file:

`<script src="//code.highcharts.com/highcharts-3d.js"></script>`

Thanks!

**Comment by marcaube** [comment]
Thanks @tiranflorin!

I'm definitely going to note that in the docs when I have a bit of time.
