### ISSUE TITLE
Unknown "chart" function

### ISSUE THREAD

**Issue by kusflo** [marcaube/ObHighchartsBundle#90]
I am using synfony2.8 and I have this problem when playing the sample document:
**Unknown "chart" function in ExampleBundle:Default:index.html.twig at line 20.**

`$env = $this->parser->getEnvironment();
        if (false === $function = $env->getFunction($name)) {
            $e = new Twig_Error_Syntax(sprintf('Unknown "%s" function.', $name), $line, $this->parser->getFilename());
            $e->addSuggestions($name, array_keys($env->getFunctions()));
            throw $e;`

**Comment by marcaube** [comment]
Hi @kusflo,

I've installed a fresh Symfony 2.8, then installed the bundle, registered it in AppKernel and everything just works. Have you followed the [installation instructions](https://github.com/marcaube/ObHighchartsBundle/blob/master/Resources/doc/installation.md) ?

The `chart` function is added when the bundle is registered in `AppKernel.php`.
